version: "3.7"

services:
  mysql:
    image: mysql:8.0-debian
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    ports:
      #image port: local physical port
      - 3306:3306
      - 33060:33060
    restart: always
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    #  - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
    #  (initial with data)
    environment:
      MYSQL_ROOT_PASSWORD: root

#
#  pawn:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    restart: always
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8080"
#    environment:
#      MYSQL_HOST: mysql